version: '3'
services: 
   update: 
      build:
         context: . 
         args:
            ROOT_PW: 1234
            USER_PW: 2345
      container_name: Update_Server
      ports:  
         - 2022:2022
      volumes:  
         - /opt/Docker_Volume/update/hanktemp:/automnt/hanktemp
